apiVersion: v1
kind: Service
metadata:
  name: {{ template "translatortext.fullname" . }}
  labels:
    app: {{ template "translatortext.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ template "translatortext.fullname" . }}
